spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/companydata?serverTimezone=JST&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

server:
  port: 8080
#  context-path: /api
logging:
  level:
    root: info
    com.lrm: debug
  file: logs/debug.log

mybatis:
  mapper-locations: classpath:mappers/UserMapper.xml
  type-aliases-package: com.sutest512.entity






